---
title: "Localizing Responses"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Localizing Responses}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(within1)
```

When a user submits a swim report, we generate a response based on that submission.
For example, imagine we received this row of data from a user.

```{r sample-row}
submission <- tibble::tibble(
  name = "Thomas",
  where = "seashore",
  temp = 27
)
```

We send them a response, letting them know how their report compares to our other reports.

```{r comparison}
submission <- submission %>% 
  localize_beach() %>% 
  celsify_temp()

infile <- "swim.csv"
other_reports <- readr::read_csv(
  infile, 
  col_types = readr::cols(name = "c", where = "c", temp = "d")
) %>% 
  localize_beach() %>% 
  celsify_temp()
  
avg_temp <- mean(other_reports$temp)

relative_temp <- dplyr::case_when(
  submission$temp > avg_temp ~ "higher than",
  submission$temp < avg_temp ~ "lower than",
  TRUE ~ "the same as"
)

response <- glue::glue(
  "Thanks, {name}!",
  "Your submission is {relative_temp} the average temperature!",
  name = submission$name,
  relative_temp = relative_temp,
  .sep = " "
)
response
```
