
# Welcome {-}

This book is a companion to [R Packages](https://r-pkgs.org/), by Hadley Wickham and Jennifer Bryan, and aims to support the reader through a full read-through of the R Packages book. It aims to set out learning objectives as well as collect common questions and answers.

This book is a work in progress, and being compiled alongside the first cohort(s) of the R4DS R Packages Book Club. Recordings for the accompanying presentations can be seen on [this YouTube playlist](https://www.youtube.com/playlist?list=PL3x6DOfs2NGiXMln8bxY7e0XgA5z1cp-8).

## Parts of this Companion {-}

:::LO
This box outlines some **Learning Objectives** for each chapter.

For example:

- Identify reasons that you might write a package.
- Become familiar with all of the parts of an R package.
:::

:::question
This box denotes a question!
:::

:::TODO
This box means the supplied answer to the question is fuzzy and could use some work! We love PRs if you'd like to help with documentation!
:::


## Suggested Order {-}

We believe there is a better (idea-based) order in which this book should be read (for example, by a book club):

**Why should I read this book?**

* Chapter 1: Introduction
* Chapter 2: The whole game

**How do I set up my system and get started?**

* Chapter 3: System setup
* Chapter 4: Package structure and state

**How should I work on my package?**

* Chapter 5: Fundamental development workflows
* Chapter 18: Git and GitHub

**How do I convert a script to a package?**

* Chapter 6: The package within
* Chapter 11: Vignettes: long-form documentation

**How do I write functions and document them?**

* Chapter 7: R code
* Chapter 10: Object documentation
* Chapter 13: Namespace

**How do I make sure my package works?**

* Chapter 12: Testing
* Chapter 19: Automated checking

**How do I describe my package?**

* Chapter 8: Package metadata
* Chapter 9: Licensing

**How do I include things like data or other files?**

* Chapter 14: External data
* Chapter 16: Installed files

**How do I use compiled code and other obscure package-y things?**

* Chapter 15: Compiled code
* Chapter 17: Other components

**How do I release my package?**

* Chapter 20: Releasing a package
